version: '3'

services:

  servidor_mysql:
    hostname: servidor_mysql
    container_name: servidor_mysql
    image: mysql:5.7.40
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d 
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: 4G
    restart: always
    environment:
      - MYSQL_DATABASE=dbrotas
      - MYSQL_ROOT_PASSWORD=Rs5kD85DQk6
      - MYSQL_USER=user2
      - MYSQL_PASSWORD=2Rs5kD85DQk6
      - TZ=America/Sao_Paulo
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h servidor_mysql -u root -pRs5kD85DQk6 || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 5
    networks:
      - my_network

  flask_app:
    build:
      context: .
      dockerfile: back/Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/src/app
    depends_on:
      servidor_mysql:
        condition: "service_healthy"
    networks:
      - my_network

volumes:
  mysql:

networks:
  my_network:
